### PR TITLE
New notification indicators

### PR DESCRIPTION
**Pull request by AI-ien**
Made some changes to notifications indicators. This PR will solve confusing default clipboard icons and will add DnD:
* added missing status *notifications disabled* or *Do not Disturb* status
* added new bell icon styles
* placed icons under *icons* folder to avoid missing icons if host system does not have them

These icons are activated for split calendar/notification case. When calendar/notifications are merged (default Gnome) then I left the same behavior as in Gnome, so the icon is a dot when there is a notification or hidden in case of no notifications, plus disabled notification icon when DnD. It's up to you to leave like this or change like in split case, but I think it is more appropriate leave like this. In any case it is easy to change.

This will also fix issue #48

### CODE REVIEW

**Comment by Ordissimo** [comment]
Hi @AI-ien,
Thank's for your work!
I removed the icons from the project (https://github.com/Fausto-Korpsvart/Big-Sur-StatusArea/tree/master/icons) to use the icons provided by the systems, some users complained about the inconsistency of the icons with their theme.
I would prefer the icons you provide as a fallback.

**Comment by AI-ien** [comment]
I would agree if Adwaita had a dedicated notification icons. Who ever complained about inconsistency was wrong or was actually using custom icon pack. Currently default used icons are `task-due-symbolic` and `task-past-due-symbolic`, none is related with notifications. This actually creates the opposite effect of consistency because of confusing task icons in place of notifications.

**Comment by Ordissimo** [comment]
Thanks for the contribution!

**Comment by Ordissimo** [comment]
Hi @AI-ien ,
I like it very much!

**Comment by AI-ien** [comment]
Somehow update v34 pushed without icons.

**Comment by Ordissimo** [comment]
@AI-ien, Fixed in v35

**Pull request merged**
