### PR TITLE
Created a swedish translation

### PR DESCRIPTION
**Pull request by ThisIsMemeboi**
Created a Swedish translation. Might need some fine tuning once published.

### CODE REVIEW

**Comment by Ordissimo** [comment]
Hi @ThisIsMemeboi ,
Thank you for your contribution!
Can you merge request #71 with #70?

**Comment by ThisIsMemeboi** [comment]
I can try to, I'm quite new to GitHub so I don't really know how to, but I'll see what I can do

**Comment by Ordissimo** [comment]
@ThisIsMemeboi ,
Directly on git, you switch on the branch, you modify the file and you validate.

**Comment by ThisIsMemeboi** [comment]
I don't think I understand....

**Comment by Ordissimo** [comment]
@ThisIsMemeboi,
Lee message is gone with delay, I will continue to search, but I do not reproduce the problem!

**Comment by ThisIsMemeboi** [comment]
What do you mean issue? There's nothing wrong, it's just that I don't know how to switch a branch, or what it even means because I'm new to GitHub.

**Comment by Ordissimo** [comment]
@ThisIsMemeboi 
Message thread error (Sorry):
> The message is gone with delay, I will continue to search, but I do not reproduce the problem!

**Pull request closed without merging**
